# Generated by Django 4.1.7 on 2023-04-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_bb_users_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='users_bookmarks',
        ),
    ]
