# Generated by Django 4.1.6 on 2023-02-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_bb_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='user',
        ),
    ]
