# Generated by Django 4.1.7 on 2023-04-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_remove_bb_users_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
